<Project>
  <Import Project="../Directory.Build.props"/>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1515;CA1707;CA2007;CA1305</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>
</Project>
